### ISSUE TITLE
Advertise that impress.js needs to be patched until upstream doesn't accept the pull request

### ISSUE THREAD

**Issue by pachi** [m42e/impress.js-progress#3]
Until https://github.com/m4n2b/impress.js/commit/f367c842b85ef8ea133e7760f601d1d6c2877e9d isn't accepted there's the need to patch js/impress.js to add the steps data to init().

Changing line 402 like this:
-            triggerEvent(root, "impress:init", { api: roots[ "impress-root-" + rootId ] });
-            triggerEvent(root, "impress:init", { api: roots[ "impress-root-" + rootId ], steps: steps });

**Comment by m42e** [comment]
Ok the link to the tickets aren't enough? Sorry I missed these tickets Damn!
